module.exports = {
  testEnvironment: 'jsdom',
  setupFiles: ['<rootDir>/jest.setup.ts'],
  transform: { '^.+\\.[jt]sx?$': ['babel-jest', { configFile: './babel.config.js' }] },
  transformIgnorePatterns: ['node_modules/'],
  moduleNameMapper: {
    '^react-native$': '<rootDir>/__mocks__/react-native.ts',
    '^react-native-safe-area-context$': '<rootDir>/__mocks__/react-native-safe-area-context.ts',
    '^expo-constants$': '<rootDir>/__mocks__/expo-constants.ts',
    '^expo-router$': '<rootDir>/__mocks__/expo-router.ts',
    '^expo-modules-core$': '<rootDir>/__mocks__/expo-modules-core.ts',
    '^expo/virtual/env\\.js$': '<rootDir>/__mocks__/expo-virtual-env.ts',
    '^expo-asset$': '<rootDir>/__mocks__/expo-asset.ts',
    '^expo-font$': '<rootDir>/__mocks__/expo-font.ts',
    '^expo-image$': '<rootDir>/__mocks__/expo-image.ts',
    '^expo-linear-gradient$': '<rootDir>/__mocks__/expo-linear-gradient.ts',
    '^expo-status-bar$': '<rootDir>/__mocks__/expo-status-bar.ts',
    '^expo-haptics$': '<rootDir>/__mocks__/expo-haptics.ts',
    '^expo-secure-store$': '<rootDir>/__mocks__/expo-secure-store.ts',
    '^expo-splash-screen$': '<rootDir>/__mocks__/expo-splash-screen.ts',
    '^expo-linking$': '<rootDir>/__mocks__/expo-linking.ts',
    '^expo$': '<rootDir>/__mocks__/expo.ts',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  testMatch: ['**/__tests__/**/*.test.(ts|tsx)'],
};
