export interface RawBackendProduct {
  id: string;
  code: string;
  name: string;
  category: string;
  price: number;
  cost_price: number;
  unit: string;
  is_active: boolean;
  options?: any[];
  vat_rate?: number;
  image_url?: string;
}

export const DEFAULT_POS_PRODUCTS: RawBackendProduct[] = [
  // ── SỮA CHUA ──
  {
    id: 'pos_sc01',
    code: 'SC01',
    name: 'Sữa chua đánh đá',
    category: 'SỮA CHUA',
    price: 20000,
    cost_price: 8000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_sc02',
    code: 'SC02',
    name: 'Sữa chua mít',
    category: 'SỮA CHUA',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_sc03',
    code: 'SC03',
    name: 'Sữa chua trân châu',
    category: 'SỮA CHUA',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_sc04',
    code: 'SC04',
    name: 'Sữa chua thạch',
    category: 'SỮA CHUA',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_sc05',
    code: 'SC05',
    name: 'Sữa chua việt quất',
    category: 'SỮA CHUA',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_sc06',
    code: 'SC06',
    name: 'Sữa chua dâu',
    category: 'SỮA CHUA',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_sc07',
    code: 'SC07',
    name: 'Sữa chua hoa quả',
    category: 'SỮA CHUA',
    price: 30000,
    cost_price: 12000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },

  // ── TRÀ CHANH ──
  {
    id: 'pos_tc01',
    code: 'TC01',
    name: 'Trà chanh truyền thống',
    category: 'TRÀ CHANH',
    price: 10000,
    cost_price: 3000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 15000 }],
  },
  {
    id: 'pos_tc02',
    code: 'TC02',
    name: 'Trà chanh dưa lưới',
    category: 'TRÀ CHANH',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },
  {
    id: 'pos_tc03',
    code: 'TC03',
    name: 'Trà ổi hồng chanh leo',
    category: 'TRÀ CHANH',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_tc04',
    code: 'TC04',
    name: 'Trà chanh leo đào',
    category: 'TRÀ CHANH',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_tc05',
    code: 'TC05',
    name: 'Trà chanh dâu',
    category: 'TRÀ CHANH',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },
  {
    id: 'pos_tc06',
    code: 'TC06',
    name: 'Trà chanh đào',
    category: 'TRÀ CHANH',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },

  // ── ĐỒ ĂN VẶT ──
  {
    id: 'pos_dv01',
    code: 'DV01',
    name: 'Xúc xích',
    category: 'ĐỒ ĂN VẶT',
    price: 10000,
    cost_price: 5000,
    unit: 'Cái',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv02',
    code: 'DV02',
    name: 'Viên chiên củ quả',
    category: 'ĐỒ ĂN VẶT',
    price: 30000,
    cost_price: 12000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv03',
    code: 'DV03',
    name: 'Nem chua rán',
    category: 'ĐỒ ĂN VẶT',
    price: 30000,
    cost_price: 12000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv04',
    code: 'DV04',
    name: 'Khoai tây chiên',
    category: 'ĐỒ ĂN VẶT',
    price: 30000,
    cost_price: 10000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv05',
    code: 'DV05',
    name: 'Khoai tây chiên lắc phô mai',
    category: 'ĐỒ ĂN VẶT',
    price: 30000,
    cost_price: 12000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv06',
    code: 'DV06',
    name: 'Khoai lang kén',
    category: 'ĐỒ ĂN VẶT',
    price: 30000,
    cost_price: 12000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv07',
    code: 'DV07',
    name: 'Phô mai que',
    category: 'ĐỒ ĂN VẶT',
    price: 30000,
    cost_price: 12000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv08',
    code: 'DV08',
    name: 'Khoai môn lệ phố',
    category: 'ĐỒ ĂN VẶT',
    price: 30000,
    cost_price: 12000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_dv09',
    code: 'DV09',
    name: 'Mẹt thập cẩm',
    category: 'ĐỒ ĂN VẶT',
    price: 50000,
    cost_price: 20000,
    unit: 'Mẹt',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 100000 }],
  },
  {
    id: 'pos_dv10',
    code: 'DV10',
    name: 'Chân gà sốt Thái',
    category: 'ĐỒ ĂN VẶT',
    price: 50000,
    cost_price: 25000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 100000 }],
  },
  {
    id: 'pos_dv11',
    code: 'DV11',
    name: 'Nem nướng',
    category: 'ĐỒ ĂN VẶT',
    price: 40000,
    cost_price: 18000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },

  // ── CHÈ ──
  {
    id: 'pos_che01',
    code: 'CHE01',
    name: 'Chè bưởi',
    category: 'CHÈ',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },
  {
    id: 'pos_che02',
    code: 'CHE02',
    name: 'Chè thập cẩm',
    category: 'CHÈ',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },
  {
    id: 'pos_che03',
    code: 'CHE03',
    name: 'Chè ba màu',
    category: 'CHÈ',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },
  {
    id: 'pos_che04',
    code: 'CHE04',
    name: 'Chè Huế',
    category: 'CHÈ',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },
  {
    id: 'pos_che05',
    code: 'CHE05',
    name: 'Chè đậu đỏ',
    category: 'CHÈ',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 20000 }],
  },
  {
    id: 'pos_che06',
    code: 'CHE06',
    name: 'Chè thạch dừa',
    category: 'CHÈ',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_che07',
    code: 'CHE07',
    name: 'Chè Thái',
    category: 'CHÈ',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_che08',
    code: 'CHE08',
    name: 'Chè Thái sầu riêng',
    category: 'CHÈ',
    price: 30000,
    cost_price: 14000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_che09',
    code: 'CHE09',
    name: 'Chè mít hạt đác',
    category: 'CHÈ',
    price: 30000,
    cost_price: 14000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },

  // ── TRÀ SỮA ──
  {
    id: 'pos_ts01',
    code: 'TS01',
    name: 'Trà sữa truyền thống',
    category: 'TRÀ SỮA',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_ts02',
    code: 'TS02',
    name: 'Trà sữa dâu',
    category: 'TRÀ SỮA',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_ts03',
    code: 'TS03',
    name: 'Trà sữa việt quất',
    category: 'TRÀ SỮA',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_ts04',
    code: 'TS04',
    name: 'Trà sữa socola',
    category: 'TRÀ SỮA',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_ts05',
    code: 'TS05',
    name: 'Trà sữa khoai môn',
    category: 'TRÀ SỮA',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_ts06',
    code: 'TS06',
    name: 'Trà sữa matcha',
    category: 'TRÀ SỮA',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_ts07',
    code: 'TS07',
    name: 'Trà sữa dưa lưới',
    category: 'TRÀ SỮA',
    price: 20000,
    cost_price: 7000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 25000 }],
  },
  {
    id: 'pos_ts08',
    code: 'TS08',
    name: 'Trà sữa kem trứng',
    category: 'TRÀ SỮA',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 30000 }],
  },
  {
    id: 'pos_ts09',
    code: 'TS09',
    name: 'Trà sữa đường đen',
    category: 'TRÀ SỮA',
    price: 25000,
    cost_price: 10000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [{ type: 'size', name: 'L', price: 30000 }],
  },

  // ── SODA ──
  {
    id: 'pos_sd01',
    code: 'SD01',
    name: 'Soda',
    category: 'SODA',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
    options: [
      { type: 'size', name: 'L', price: 20000 },
      { type: 'topping', name: 'Vị dâu', price: 0 },
      { type: 'topping', name: 'Vị bạc hà', price: 0 },
      { type: 'topping', name: 'Vị chanh', price: 0 },
      { type: 'topping', name: 'Vị đào', price: 0 },
      { type: 'topping', name: 'Vị blue', price: 0 },
    ],
  },

  // ── KEM ──
  {
    id: 'pos_km01',
    code: 'KM01',
    name: 'Kem ly',
    category: 'KEM',
    price: 15000,
    cost_price: 5000,
    unit: 'Ly',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_km02',
    code: 'KM02',
    name: 'Kem xôi',
    category: 'KEM',
    price: 15000,
    cost_price: 5000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
  },
  {
    id: 'pos_km03',
    code: 'KM03',
    name: 'Kem vị',
    category: 'KEM',
    price: 15000,
    cost_price: 5000,
    unit: 'Phần',
    is_active: true,
    vat_rate: 8,
    options: [
      { type: 'topping', name: 'Vị dâu', price: 0 },
      { type: 'topping', name: 'Vị bạc hà', price: 0 },
      { type: 'topping', name: 'Vị socola', price: 0 },
      { type: 'topping', name: 'Vị việt quất', price: 0 },
    ],
  },
];
