"""add_indexes_to_orders_products

Revision ID: 8529c76ae78f
Revises: add_notification_log
Create Date: 2026-07-14 02:23:39.172479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def get_safe_default(column):
    t = column.type
    if isinstance(t, (sa.Numeric, sa.Float, sa.Integer)):
        return sa.text('0')
    elif isinstance(t, (sa.String, sa.Text)):
        return sa.text("''")
    elif isinstance(t, sa.Boolean):
        return sa.text('false')
    elif isinstance(t, (sa.DateTime, sa.Date)):
        return sa.func.now()
    elif isinstance(t, sa.UUID):
        return sa.text('gen_random_uuid()')
    return None

def safe_create_table(table_name, *args, **kwargs):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    schema = kwargs.get('schema', None)
    try:
        tables = inspector.get_table_names(schema=schema)
    except Exception:
        tables = []
    if table_name not in tables:
        op.create_table(table_name, *args, **kwargs)
    else:
        # Check if columns are missing
        columns = [c['name'] for c in inspector.get_columns(table_name, schema=schema)]
        for arg in args:
            if isinstance(arg, sa.Column):
                if arg.name not in columns:
                    # Inject safe default if NOT NULL is specified without a default
                    if not arg.nullable and arg.server_default is None:
                        d = get_safe_default(arg)
                        if d is not None:
                            arg.server_default = sa.DefaultClause(d)
                    op.add_column(table_name, arg, schema=schema)

def safe_create_index(index_name, table_name, columns, **kwargs):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    schema = kwargs.get('schema', None)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name, schema=schema)]
    except Exception:
        indexes = []
    if index_name not in indexes:
        op.create_index(index_name, table_name, columns, **kwargs)

def safe_create_unique_constraint(constraint_name, table_name, columns, **kwargs):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    schema = kwargs.get('schema', None)
    try:
        constraints = [c['name'] for c in inspector.get_unique_constraints(table_name, schema=schema)]
    except Exception:
        constraints = []
    if constraint_name not in constraints:
        op.create_unique_constraint(constraint_name, table_name, columns, **kwargs)

def safe_create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols, **kwargs):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    source_schema = kwargs.get('source_schema', None)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(source_table, schema=source_schema)]
    except Exception:
        fks = []
    if constraint_name not in fks:
        op.create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols, **kwargs)
# revision identifiers, used by Alembic.
revision: str = '8529c76ae78f'
down_revision: Union[str, None] = 'add_notification_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('cashier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ban_hang'
    )
    safe_create_index(op.f('ix_ban_hang_orders_branch_id'), 'orders', ['branch_id'], unique=False, schema='ban_hang')
    safe_create_index(op.f('ix_ban_hang_orders_cashier_id'), 'orders', ['cashier_id'], unique=False, schema='ban_hang')
    safe_create_index(op.f('ix_ban_hang_orders_status'), 'orders', ['status'], unique=False, schema='ban_hang')
    safe_create_index(op.f('ix_ban_hang_orders_table_id'), 'orders', ['table_id'], unique=False, schema='ban_hang')
    safe_create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='ban_hang'
    )
    safe_create_index(op.f('ix_ban_hang_products_branch_id'), 'products', ['branch_id'], unique=False, schema='ban_hang')
    safe_create_index(op.f('ix_ban_hang_products_created_at'), 'products', ['created_at'], unique=False, schema='ban_hang')
    safe_create_index(op.f('ix_ban_hang_products_is_active'), 'products', ['is_active'], unique=False, schema='ban_hang')
    safe_create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('printer_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='ban_hang'
    )
    safe_create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ban_hang'
    )
    safe_create_table('cash_register_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('invoice_code', sa.String(length=23), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_tax_code', sa.String(length=20), nullable=True),
    sa.Column('buyer_personal_id', sa.String(length=20), nullable=True),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('adjustment_of', sa.UUID(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=10), nullable=True),
    sa.Column('tax_auth_status', sa.String(length=20), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('delivery_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_cash_register_invoices_invoice_code'), 'cash_register_invoices', ['invoice_code'], unique=True, schema='ke_toan')
    safe_create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=24), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_tax_code', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_invoices_token'), 'invoices', ['token'], unique=True, schema='ke_toan')
    safe_create_table('so_s1a',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('revenue_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_so_s1a_period_month'), 'so_s1a', ['period_month'], unique=False, schema='ke_toan')
    safe_create_table('so_s2a',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('product_category', sa.String(length=20), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('tncn_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_so_s2a_period_month'), 'so_s2a', ['period_month'], unique=False, schema='ke_toan')
    safe_create_table('so_s2b',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_so_s2b_period_month'), 'so_s2b', ['period_month'], unique=False, schema='ke_toan')
    safe_create_table('so_s2c',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_of_goods', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('other_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_so_s2c_period_month'), 'so_s2c', ['period_month'], unique=False, schema='ke_toan')
    safe_create_table('so_s2d',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('opening_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inbound_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outbound_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_so_s2d_period_month'), 'so_s2d', ['period_month'], unique=False, schema='ke_toan')
    safe_create_table('so_s2e',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('bank_account', sa.String(length=50), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('inflow', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('outflow', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_so_s2e_period_month'), 'so_s2e', ['period_month'], unique=False, schema='ke_toan')
    safe_create_table('so_s3a',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('payable', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('signed_by', sa.String(length=100), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_index(op.f('ix_ke_toan_so_s3a_period_month'), 'so_s3a', ['period_month'], unique=False, schema='ke_toan')
    safe_create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ke_toan'
    )
    safe_create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_alert', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='quan_ly'
    )
    safe_create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avg_cost_backfilled', sa.Boolean(), nullable=False),
    sa.Column('accounting_period', sa.String(length=7), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='quan_ly'
    )
    safe_create_table('raw_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('default_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='quan_ly'
    )
    safe_create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('yield_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('yield_unit', sa.String(length=20), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('wastage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='quan_ly'
    )
    safe_create_table('shift_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('shift_code', sa.String(length=20), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cash_end', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('card_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('transfer_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expense_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='quan_ly'
    )
    safe_create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=20), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='quan_ly'
    )
    safe_create_table('declaration_deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('reminded_14', sa.Boolean(), nullable=False),
    sa.Column('reminded_7', sa.Boolean(), nullable=False),
    sa.Column('reminded_3', sa.Boolean(), nullable=False),
    sa.Column('reminded_1', sa.Boolean(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='thue'
    )
    safe_create_table('hkd_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('tax_code', sa.String(length=14), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('registration_status', sa.String(length=20), nullable=False),
    sa.Column('tax_method', sa.String(length=20), nullable=False),
    sa.Column('revenue_ytd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('opened_in_first_half', sa.Boolean(), nullable=False),
    sa.Column('threshold_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='thue'
    )
    safe_create_index(op.f('ix_thue_hkd_profiles_tax_code'), 'hkd_profiles', ['tax_code'], unique=False, schema='thue')
    safe_create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='thue'
    )
    safe_create_table('notified_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('tax_code', sa.String(length=14), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('wallet_type', sa.String(length=20), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('form_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='thue'
    )
    safe_create_index(op.f('ix_thue_notified_bank_accounts_tax_code'), 'notified_bank_accounts', ['tax_code'], unique=False, schema='thue')
    safe_create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('order_round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ban_hang.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ban_hang'
    )
    safe_create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['quan_ly.suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number'),
    schema='quan_ly'
    )
    safe_create_table('recipe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('raw_material_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['quan_ly.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='quan_ly'
    )
    safe_create_table('recipe_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['quan_ly.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='quan_ly'
    )
    safe_create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('raw_material_id', sa.UUID(), nullable=True),
    sa.Column('raw_material_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['quan_ly.purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='quan_ly'
    )
    op.drop_index('ix_notification_logs_branch_created', table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_create_table('notification_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=16), server_default=sa.text("'in_app'::character varying"), autoincrement=False, nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('ref_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('delivered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='notification_logs_pkey')
    )
    safe_create_index('ix_notification_logs_branch_created', 'notification_logs', ['branch_id', 'created_at'], unique=False)
    op.drop_table('purchase_order_items', schema='quan_ly')
    op.drop_table('recipe_versions', schema='quan_ly')
    op.drop_table('recipe_items', schema='quan_ly')
    op.drop_table('purchase_orders', schema='quan_ly')
    op.drop_table('order_items', schema='ban_hang')
    op.drop_index(op.f('ix_thue_notified_bank_accounts_tax_code'), table_name='notified_bank_accounts', schema='thue')
    op.drop_table('notified_bank_accounts', schema='thue')
    op.drop_table('notification_logs', schema='thue')
    op.drop_index(op.f('ix_thue_hkd_profiles_tax_code'), table_name='hkd_profiles', schema='thue')
    op.drop_table('hkd_profiles', schema='thue')
    op.drop_table('declaration_deadlines', schema='thue')
    op.drop_table('suppliers', schema='quan_ly')
    op.drop_table('shift_logs', schema='quan_ly')
    op.drop_table('recipes', schema='quan_ly')
    op.drop_table('raw_materials', schema='quan_ly')
    op.drop_table('inventory_transactions', schema='quan_ly')
    op.drop_table('inventory', schema='quan_ly')
    op.drop_table('transactions', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_so_s3a_period_month'), table_name='so_s3a', schema='ke_toan')
    op.drop_table('so_s3a', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_so_s2e_period_month'), table_name='so_s2e', schema='ke_toan')
    op.drop_table('so_s2e', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_so_s2d_period_month'), table_name='so_s2d', schema='ke_toan')
    op.drop_table('so_s2d', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_so_s2c_period_month'), table_name='so_s2c', schema='ke_toan')
    op.drop_table('so_s2c', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_so_s2b_period_month'), table_name='so_s2b', schema='ke_toan')
    op.drop_table('so_s2b', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_so_s2a_period_month'), table_name='so_s2a', schema='ke_toan')
    op.drop_table('so_s2a', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_so_s1a_period_month'), table_name='so_s1a', schema='ke_toan')
    op.drop_table('so_s1a', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_invoices_token'), table_name='invoices', schema='ke_toan')
    op.drop_table('invoices', schema='ke_toan')
    op.drop_index(op.f('ix_ke_toan_cash_register_invoices_invoice_code'), table_name='cash_register_invoices', schema='ke_toan')
    op.drop_table('cash_register_invoices', schema='ke_toan')
    op.drop_table('tables', schema='ban_hang')
    op.drop_table('stations', schema='ban_hang')
    op.drop_index(op.f('ix_ban_hang_products_is_active'), table_name='products', schema='ban_hang')
    op.drop_index(op.f('ix_ban_hang_products_created_at'), table_name='products', schema='ban_hang')
    op.drop_index(op.f('ix_ban_hang_products_branch_id'), table_name='products', schema='ban_hang')
    op.drop_table('products', schema='ban_hang')
    op.drop_index(op.f('ix_ban_hang_orders_table_id'), table_name='orders', schema='ban_hang')
    op.drop_index(op.f('ix_ban_hang_orders_status'), table_name='orders', schema='ban_hang')
    op.drop_index(op.f('ix_ban_hang_orders_cashier_id'), table_name='orders', schema='ban_hang')
    op.drop_index(op.f('ix_ban_hang_orders_branch_id'), table_name='orders', schema='ban_hang')
    op.drop_table('orders', schema='ban_hang')
    # ### end Alembic commands ###
